alias bbb_aws='ssh ubuntu@ec2-35-182-222-4.ca-central-1.compute.amazonaws.com'
alias orange_pi='ssh michael@192.168.0.102'
alias gps_cloud='ssh michael@35.203.51.139'
alias juno="jupyter notebook"
alias jn="jupyter notebook"
alias my_rvm="rvm 2.4.2@plot_doc"
alias p32="workon plot3py2"
alias p33="workon plot3py3"
alias p22="workon plot2py2"
alias p23="workon plot2py3"
alias py3="workon plotly.py3"
alias gmn="sudo systemctl start garmin.service"
alias serve_docs="bundle exec jekyll serve --config _config_dev.yml"
alias serve_test="bundle exec jekyll serve --config _config_test.yml"
alias md="workon retext && retext"
alias pdocs="workon docs"
alias julo="jupyter lab"
alias jl="jupyter lab"
alias ip="ipython"
alias scratch="cd ~/plotly/plotly\ scratch/community/"
alias px="cd ~/plotly/plotly\ scratch/community/px"
alias docs="cd ~/plotly/repos/documentation"
alias jj="source activate jj-dash-27"
alias repos="cd /home/michael/plotly/repos"
alias sql_test="mysql -u root -p"
alias set-google-gps-project="gcloud config set project gps-dashboard-208819"
alias liberty="cd /home/michael/dokku-apps/liberty-search"
alias jon_server="ssh michaelbabyn@usagitsukino.duckdns.org"
alias snp='cd ~/plotly/SOWs/S\&P/'
alias atl='cd ~/atelier'
alias banq_login='curl -d user=00855481 -d password=37725314 https://banq-wlc.banq.qc.ca/auth/index.html'
alias octave='flatpak run org.octave.Octave'
alias plotly_io="rvm 2.4.2@plotly_io"
